// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbsFdjZKSF93GDchj7R400cDEebtV968w',
    appId: '1:1031335782090:web:7686f74e50e5161d6a3633',
    messagingSenderId: '1031335782090',
    projectId: 'whatz-up-894fd',
    authDomain: 'whatz-up-894fd.firebaseapp.com',
    storageBucket: 'whatz-up-894fd.appspot.com',
    measurementId: 'G-T4RHNHPTQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDctgwJQBB8W4thi7n4nBt-C5l7ElTdIWg',
    appId: '1:1031335782090:android:2cd7c824b7c71b146a3633',
    messagingSenderId: '1031335782090',
    projectId: 'whatz-up-894fd',
    storageBucket: 'whatz-up-894fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkgEP1lCrtoELOKwar8tucoGyHFIUgnek',
    appId: '1:1031335782090:ios:c8ab2f7d1c3e29326a3633',
    messagingSenderId: '1031335782090',
    projectId: 'whatz-up-894fd',
    storageBucket: 'whatz-up-894fd.appspot.com',
    iosBundleId: 'com.example.whatzUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkgEP1lCrtoELOKwar8tucoGyHFIUgnek',
    appId: '1:1031335782090:ios:5930d9c02cf695e26a3633',
    messagingSenderId: '1031335782090',
    projectId: 'whatz-up-894fd',
    storageBucket: 'whatz-up-894fd.appspot.com',
    iosBundleId: 'com.example.whatzUp.RunnerTests',
  );
}
